version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    image: ${IMAGE_TAG}
    restart: unless-stopped
    env_file: .env.production
    environment:
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - strapi-src:/opt/app/src
      - strapi-types:/opt/app/types
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - "1338:1338"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env.production
    image: postgres:latest
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    command: -p 5433
    ports:
      - "5433:5433"
    networks:
      - strapi

volumes:
  strapi-data:
  strapi-uploads:
  strapi-src:
  strapi-types:

networks:
  strapi:
    name: Strapi
    driver: bridge